### ISSUE TITLE
doesn't build with kernel 4.14

### ISSUE THREAD

**Issue by CvH** [braice/MuMuDVB#195]
MuMuDVB doesn't build anymore due the drop of `CA_SET_PID` at linux kernel >=4.14
https://github.com/torvalds/linux/commit/833ff5e7feda1a042b83e82208cef3d212ca0ef1 (at least I guess it is due that drop)
```
...
                 from /builddir/mumudvb-b3c9ae7/src/mumudvb.c:117:
/builddir/mumudvb-b3c9ae7/src/scam_common.h:72:3: error: unknown type name 'ca_pid_t'
   ca_pid_t ca_pid;
   ^~~~~~~~
make[2]: *** [Makefile:491: mumudvb.o] Error 1
In file included from /builddir/mumudvb-b3c9ae7/src/scam_capmt.h:44:0,
                 from /builddir/mumudvb-b3c9ae7/src/mumudvb_mon.c:46:
/builddir/mumudvb-b3c9ae7/src/scam_common.h:72:3: error: unknown type name 'ca_pid_t'
   ca_pid_t ca_pid;
   ^~~~~~~~
make[2]: *** [Makefile:491: mumudvb_mon.o] Error 1
```

**Comment by braice** [comment]
Hello

Indeed you are right,

The structure is useful but the CA_SET_PID was in case we got the request
from the driver. I am not a big expert in SCAM so I hope my dirty patch
does not also break scam support in recent kernels.

Anyway try the last version and tell me if it works

Thank you



2017-11-25 5:30 GMT-05:00 CvH <notifications@github.com>:

**Comment by CvH** [comment]
At least it works for kernel 4.14 :) But I have no hw to runtime test it.
TX !

**Comment by ukleinek** [comment]
FTR: The workaround is commit 596f7dbebd2590f7e77cf755af46952f340ddb97

**Comment by braice** [comment]
Thank you,

Can you please make a pull request

**Comment by gredek** [comment]
what about the functionality in scam_getcw.c with the removal of the ca_set_pid in >= 4.14 kernels? Is in older kernels scam was working fine

SCAM_GETCW: output -> request: 1074294663 ca_set_pid: 1074294663 so if (*request == CA_SET_PID) statement is true in the getcwthread_func function

But with the hack the value of ca_set_pid is 42424242 (because of the workaround), so now the function checks request: 1074294663 ca_set_pid: 42424242 and that is not equal so if (*request == CA_SET_PID) statement is false in the getcwthread_func function and breaks the scam functionality

Please correct me if I'm wrong.

If I change the if statement  (*request == CA_SET_PID) to  (*request >= 0) it seems to work again. But I am no expert in these SCAM functionality so I guess it is not the right way to fix it.

**Comment by gredek** [comment]
As I am no SCAM expert I was hoping on some input/feedback on this. So I changed the if statement in the getcwthread_func function (in scam_getcw.c) , if the request id is >= 0 than the statement is true and continues. I have test this change and it seems to fix the SCAM functionality with a >= 4.14 kernel. So with this update I have a working SCAM configuration/setup again.

see for changes -> https://github.com/gredek/MuMuDVB/commit/481a53a868728392503da40f681e41a85357392d

**Comment by braice** [comment]
Thank you
