### PR TITLE
Fix broken linux build

### PR DESCRIPTION
**Pull request by anphsw**
loop initial declarations are only allowed in C99 or C11 mode (broken by 82b962af8feab5a85ebef5f1142ecd49461a69b9)
error: conflicting types for scam_vars

### CODE REVIEW

File: configure.ac [hunk 1]
```diff
@@ -18,6 +18,7 @@ fi
 
 # Checks for programs.
 AC_PROG_CC
+AC_PROG_CC_STDC
```
Comment (trollcop) [inline configure.ac:21]: I see, I removed `AC_PROG_CC_C99` as it was sait it was obsolete, but didn't think readding a replacement was needed.

Comment (anphsw) [reply configure.ac:21]: Yes, it obsoleted by newest autotools or compiler working in C99 mode as default.
But for backwards-compatibility with other build system we must left STDC keyword here or remove loop initial declarations such as "for (int i=0; i>x; i++)" to "int i; for (i=0;i>x;i++)" - no code using C99 features in project now, but only loop initial declarations in almost all files.
If we will rewrite it, code will work also with exotic compilers, as will match pure C rules.

Comment (trollcop) [reply configure.ac:21]: I'm not a big fan of `for (int i=` as I would rather declare the needed vars at beginning of scope. I would certainly be willing to run a cleanup pass removing all those, not for C99 compatibility but simply because I don't like it :)

Comment (anphsw) [reply configure.ac:21]: There is big diffirence:

Comment (anphsw) [reply configure.ac:21]: There is big difference:
C99 code:
for (int i...) {
"i" declared inside loop
}
<you cannot use "i" after loop finished>

C89 code:
int i;
"i" declared ouside loop
for (i....) {}

So next for(i.....) may not clear i after previous loop.
Such errors are happen in many big projects

Comment (trollcop) [reply configure.ac:21]: I'm aware of the implications, but a 2nd for loop not initializing the counter would be a pretty weird design pattern.
I did change some of these things during my initial large win32 refactor because some of the vars were shadowing global/outer scope vars. I just didn't replace them all.

Comment (anphsw) [reply configure.ac:21]: So if we will decide to remove STDC from autotools, we also must tune compiler flags which will actually disable c99 (as some compilers enable c99 by default, them will compile code which uses c99 features without c99-enabling flag, but others will fail without this flag).

**Comment by braice** [comment]
I can still merge this change.
I like the idea to have the loop index to be in the scope of the loop, but it is only a slight preference. So I would be OK to move them if it enables other aspects.

**Comment by Saentist** [comment]
This change make using Ubuntu 20.04 unusable without manual compilation of **automake-1.16**
ubuntu 20.04 use automake-1.15
what about older versions?

```make 
# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /opt/MuMuDVB/missing aclocal-1.16
 cd . && /bin/bash /opt/MuMuDVB/missing automake-1.16 --foreign
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /opt/MuMuDVB/missing autoconf
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create --no-recursion
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking linux/dvb/dmx.h usability... yes
checking linux/dvb/dmx.h presence... yes
checking for linux/dvb/dmx.h... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration...
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for dvbdemux_set_section_filter in -ldvbapi... yes
checking for atsc_text_segment_decode in -lucsi... yes
checking for pthread_create in -lpthread... yes
checking for clock_gettime in -lrt... yes
checking for log2l in -lm... yes
checking for atsc_text_segment_decode in -lucsi... (cached) yes
checking for en50221_tl_create in -ldvben50221... yes
checking for dvbcsa_bs_decrypt in -ldvbcsa... yes
checking for sys/types.h... (cached) yes
checking for netinet/in.h... yes
checking for arpa/nameser.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for netdb.h... (cached) yes
checking for netinet/in.h... (cached) yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking values.h usability... yes
checking values.h presence... yes
checking for values.h... yes
checking for int32_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for alarm... yes
checking for gettimeofday... yes
checking for inet_ntoa... yes
checking for memset... yes
checking for socket... yes
checking for strerror... yes
checking for strstr... yes
checking that generated files are newer than configure... done
configure: creating ./config.status

-------------------------------------------------------
MuMuDVB configure results:

Features

Build with CAM support:                             yes
Build with SCAM support:                            yes
Build with ATSC long names support:                 yes
Build with compatibility for android:                no

Debugging

Build with code coverage debug symbols               no
Build with debugging DUMA library                    no
 /bin/bash ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating src/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
Making all in src
make[1]: влизане в директория „/opt/MuMuDVB/src“
(CDPATH="${ZSH_VERSION+.}:" && cd .. && /bin/bash /opt/MuMuDVB/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd .. && /bin/bash ./config.status src/config.h
config.status: creating src/config.h
config.status: src/config.h is unchanged
make  all-am
make[2]: влизане в директория „/opt/MuMuDVB/src“
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT unicast_monit.o -MD -MP -MF .deps/unicast_monit.Tpo -c -o unicast_monit.o unicast_monit.c
mv -f .deps/unicast_monit.Tpo .deps/unicast_monit.Po
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT mumudvb_channels.o -MD -MP -MF .deps/mumudvb_channels.Tpo -c -o mumudvb_channels.o mumudvb_channels.c
In file included from /usr/include/string.h:495,
                 from mumudvb_channels.c:41:
In function ‘strncpy’,
    inlined from ‘update_chan_net’ at mumudvb_channels.c:377:5:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output may be truncated copying 64 bytes from a string of length 79 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/mumudvb_channels.Tpo .deps/mumudvb_channels.Po
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT autoconf_pat.o -MD -MP -MF .deps/autoconf_pat.Tpo -c -o autoconf_pat.o autoconf_pat.c
mv -f .deps/autoconf_pat.Tpo .deps/autoconf_pat.Po
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT autoconf_cat.o -MD -MP -MF .deps/autoconf_cat.Tpo -c -o autoconf_cat.o autoconf_cat.c
mv -f .deps/autoconf_cat.Tpo .deps/autoconf_cat.Po
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT hls.o -MD -MP -MF .deps/hls.Tpo -c -o hls.o hls.c
hls.c: In function ‘hls_entry_rotate’:
hls.c:216:6: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
  216 |      ftruncate(fileno(playlist), playlist_size);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hls.c: In function ‘hls_playlist_master’:
hls.c:307:6: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
  307 |      ftruncate(fileno(playlist), playlist_size);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/string.h:495,
                 from hls.c:20:
In function ‘strncpy’,
    inlined from ‘hls_entry_initialize’ at hls.c:135:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘hls_entry_initialize’ at hls.c:143:6:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output may be truncated copying 64 bytes from a string of length 511 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘hls_entry_initialize’ at hls.c:141:6:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output may be truncated copying 64 bytes from a string of length 511 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/hls.Tpo .deps/hls.Po
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT cam.o -MD -MP -MF .deps/cam.Tpo -c -o cam.o cam.c
mv -f .deps/cam.Tpo .deps/cam.Po
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT scam_capmt.o -MD -MP -MF .deps/scam_capmt.Tpo -c -o scam_capmt.o scam_capmt.c
mv -f .deps/scam_capmt.Tpo .deps/scam_capmt.Po
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT scam_common.o -MD -MP -MF .deps/scam_common.Tpo -c -o scam_common.o scam_common.c
mv -f .deps/scam_common.Tpo .deps/scam_common.Po
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT scam_getcw.o -MD -MP -MF .deps/scam_getcw.Tpo -c -o scam_getcw.o scam_getcw.c
mv -f .deps/scam_getcw.Tpo .deps/scam_getcw.Po
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT scam_decsa.o -MD -MP -MF .deps/scam_decsa.Tpo -c -o scam_decsa.o scam_decsa.c
mv -f .deps/scam_decsa.Tpo .deps/scam_decsa.Po
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT scam_send.o -MD -MP -MF .deps/scam_send.Tpo -c -o scam_send.o scam_send.c
mv -f .deps/scam_send.Tpo .deps/scam_send.Po
gcc -Wall -Wextra -g -O2   -o mumudvb autoconf.o crc32.o log.o multicast.o dvb.o mumudvb.o mumudvb_mon.o mumudvb_common.o network.o rewrite_pmt.o rewrite_pat.o rewrite.o rewrite_sdt.o rewrite_eit.o rtp.o sap.o ts.o t2mi.o tune.o unicast_http.o unicast_queue.o unicast_EIT.o autoconf_sdt.o autoconf_atsc.o autoconf_pmt.o autoconf_nit.o unicast_clients.o unicast_monit.o mumudvb_channels.o autoconf_pat.o autoconf_cat.o hls.o cam.o scam_capmt.o scam_common.o scam_getcw.o scam_decsa.o scam_send.o -lm -ldvbcsa -ldvben50221 -lucsi -lm -lrt -lpthread -ldvbapi
make[2]: излизане от директория „/opt/MuMuDVB/src“
make[1]: излизане от директория „/opt/MuMuDVB/src“
Making all in doc
make[1]: влизане в директория „/opt/MuMuDVB/doc“
make[1]: Няма нищо за правене за „all“.
make[1]: излизане от директория „/opt/MuMuDVB/doc“
make[1]: влизане в директория „/opt/MuMuDVB“
make[1]: Няма нищо за правене за „all-am“.
make[1]: излизане от директория „/opt/MuMuDVB“

```

**Comment by trollcop** [comment]
Are you saying AC_PROG_CC_STDC requires `automake-1.16` while AC_PROG_CC_C99 does not?

**Comment by Saentist** [comment]
> Are you saying AC_PROG_CC_STDC requires `automake-1.16` while AC_PROG_CC_C99 does not?

Before it not ask for this dependency
```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /opt/MuMuDVB/missing aclocal-1.16
 cd . && /bin/bash /opt/MuMuDVB/missing automake-1.16 --foreign```

**Comment by trollcop** [comment]
I don't understand what that means, I pulled a clean copy, did `autoreconf -i -f` followed by `./configure` and `make`, and everything is working?

According to https://packages.ubuntu.com/search?keywords=automake 20.04 uses 1.16

**Comment by anphsw** [comment]
checked AC_PROG_CC_STDC with:
$ automake --version
automake (GNU automake) 1.14.1
and 
$automake --version
automake (GNU automake) 1.15.1

Compiles without errors.

**Comment by anphsw** [comment]
> This change make using Ubuntu 20.04 unusable without manual compilation of **automake-1.16** ubuntu 20.04 use automake-1.15 what about older versions?
> 
> ```makefile
> # make
> CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /opt/MuMuDVB/missing aclocal-1.16
>  cd . && /bin/bash /opt/MuMuDVB/missing automake-1.16 --foreign
> CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /opt/MuMuDVB/missing autoconf
> /bin/bash ./config.status --recheck
It seems like problem is with ZSH as your default shell, not automake or options.
Just try to compile from bash/dash/etc.

**Comment by Saentist** [comment]
Strange my shell is bash
```bash
echo "$SHELL"
/bin/bash
```
 automake is 1.16.1

```bash
 apt list automake
Listing...
automake/focal,focal,now 1:1.16.1-4ubuntu6 all [installed]
```

Yes compilation pass, but why this message is show?

**Comment by anphsw** [comment]
Which message? I don't see any messages releated to autotools. Please paste exact string.

**Comment by Saentist** [comment]
> Which message? I don't see any messages releated to autotools. Please paste exact string.

This one

```make
# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /opt/MuMuDVB/missing aclocal-1.16
 cd . && /bin/bash /opt/MuMuDVB/missing automake-1.16 --foreign
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /opt/MuMuDVB/missing autoconf
/bin/bash ./config.status --recheck
```

**Comment by anphsw** [comment]
It seems like autotools overriding your ZSH shell with bash one. That's not an error.

**Comment by Saentist** [comment]
I think found problem
before building I run:

```
make clean
make distclean
```
**distclean** do not remove stuff generated by **autoreconf -i -f**

**Comment by trollcop** [comment]
nah, no need to remove, i was talking strictly about coding style of not
having vars in for loop definition
